# Generated by Django 4.0.6 on 2022-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
